/*
Q. Find The Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"
 
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
#include<bits/stdc++.h>
#include<iostream>
using namespace std;
char findTheDifference(string s, string t){
    
    int n = s.size();
    sort(s.begin(), s.end());
    sort(t.begin(), t.end());

    for (int i = 0; i < n; i++)
    {
        if (s[i] != t[i])
        {
            return t[i];
        }
    }
    return t[n];
}
int main(){

    string s, t;
    cin >> s >> t;

    char ans = findTheDifference(s, t);
    cout << ans;

    return 0;
}